src/carts/urls.py
from django.conf.urls import url
from .views import(
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )
app_name = 'cart'
urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/Success/$',checkout_done_view, name='Success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

#if settings.DEBUG:
#    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ecommerce/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page, guest_register_view
from addresses.views import Checkout_address_create_view, Checkout_address_reuse_view
from .views import home_page, about_page, contact_page
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from carts.views import cart_home
from carts.views import cart_detail_api_view

#from products.views import(
#        ProductListView,
#        product_list_view,
#        ProductDetailView,
#        product_detail_view,
#        ProductDetailView,
#        ProductFeaturedListView,
#        ProductFeaturedDetailView,
#        ProductDetailSlugView
#        )
urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html'), ),
    url(r'^about/$', about_page, name='about'),
    url(r'^login/$', login_page, name='login'),
    url(r'^Checkout/address/create/$', Checkout_address_create_view, name='Checkout_address_create'),
    url(r'^Checkout/address/reuse/$', Checkout_address_reuse_view, name='Checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart$', cart_detail_api_view, name='api-cart'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^register/$', register_page, name='register'),
#    url(r'^featured/$', ProductFeaturedListView.as_view()),
#    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='serach')),
#    url(r'^products-fbv/$', product_list_view),
#    url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
#    url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
#    url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
#    url(r'^cart/$', cart_home, name='cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url
from .views import(
        ProductListView,
        #product_list_view,
        #ProductDetailView,
        #product_detail_view,
        #ProductDetailView,
        #ProductFeaturedListView,
        #ProductFeaturedDetailView,
        ProductDetailSlugView
        )
app_name = 'products'
urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

#if settings.DEBUG:
#    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous"/>

src/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as product_list_url %}
{% url 'contact' as contact %}
{% url 'login' as login %}
{% url 'logout' as logout%}
{% url 'register' as register %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">{% if brand_name %} {{brand_name}} {% else %} CFE ecommerce{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact %} active {% endif %}">
        <a class="nav-link" href="{{ contact }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %} active {% endif %}">
        <a class="nav-link " href="{{ product_list_url }}">product</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == login %} active {% endif %}">
          <a class="nav-link " href="{{ logout }}">logout</a>
        </li>
      {% else %}
        <li class="nav-item {% if request.path == login %} active {% endif %}">
          <a class="nav-link " href="{{ login }}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register %} active {% endif %}">
          <a class="nav-link " href="{{ register }}">Register</a>
        </li>

      {% endif %}
      <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
        <a class="nav-link " href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>